//! TypeScript bindings for the UI (ADR 0009, spec 005 "Bindings"). The `export-bindings` bin
//! (`cargo xtask bindings`), the debug-startup export and the drift test share this code.

use std::path::{Path, PathBuf};

use specta_typescript::Typescript;
use tauri::Runtime;

use crate::specta_builder;

/// `@ts-nocheck`: the generated runtime helpers do not satisfy the UI's strict tsconfig, and
/// eslint already ignores the file.
pub const HEADER: &str =
    "// @ts-nocheck\n// Generated by wolluf-desktop (`cargo xtask bindings`). Do not edit.";

/// Relative to this crate, so the path holds wherever the repo is cloned.
pub fn committed_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../ui/src/ipc/bindings.ts")
}

/// BigInt export stays at specta-typescript's default (forbidden): a 64-bit field must break
/// the export, not silently lose precision above 2^53 in JS.
pub fn export_with<R: Runtime>(
    builder: &tauri_specta::Builder<R>,
    path: &Path,
) -> Result<(), specta_typescript::Error> {
    builder.export(Typescript::default().header(HEADER), path)
}

/// Exports the shipped command and event list; the runtime parameter does not affect the output.
pub fn export_bindings(path: &Path) -> Result<(), specta_typescript::Error> {
    export_with(&specta_builder::<tauri::Wry>(), path)
}
