/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as SkillRouteImport } from './routes/skill'
import { Route as LabelIndexRouteImport } from './routes/label.index'
import { Route as LabelProgressRouteImport } from './routes/label.progress'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsIdentityRouteImport } from './routes/settings.identity'
import { Route as SetupIndexRouteImport } from './routes/setup.index'
import { Route as SetupIdentityRouteImport } from './routes/setup.identity'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillRoute = SkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelIndexRoute = LabelIndexRouteImport.update({
  id: '/label/',
  path: '/label/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelProgressRoute = LabelProgressRouteImport.update({
  id: '/label/progress',
  path: '/label/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIdentityRoute = SettingsIdentityRouteImport.update({
  id: '/settings/identity',
  path: '/settings/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIdentityRoute = SetupIdentityRouteImport.update({
  id: '/setup/identity',
  path: '/setup/identity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recommendations': typeof RecommendationsRoute
  '/skill': typeof SkillRoute
  '/label/progress': typeof LabelProgressRoute
  '/settings/identity': typeof SettingsIdentityRoute
  '/setup/identity': typeof SetupIdentityRoute
  '/label/': typeof LabelIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recommendations': typeof RecommendationsRoute
  '/skill': typeof SkillRoute
  '/label/progress': typeof LabelProgressRoute
  '/settings/identity': typeof SettingsIdentityRoute
  '/setup/identity': typeof SetupIdentityRoute
  '/label': typeof LabelIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/setup': typeof SetupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recommendations': typeof RecommendationsRoute
  '/skill': typeof SkillRoute
  '/label/progress': typeof LabelProgressRoute
  '/settings/identity': typeof SettingsIdentityRoute
  '/setup/identity': typeof SetupIdentityRoute
  '/label/': typeof LabelIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recommendations'
    | '/skill'
    | '/label/progress'
    | '/settings/identity'
    | '/setup/identity'
    | '/label/'
    | '/settings/'
    | '/setup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recommendations'
    | '/skill'
    | '/label/progress'
    | '/settings/identity'
    | '/setup/identity'
    | '/label'
    | '/settings'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/recommendations'
    | '/skill'
    | '/label/progress'
    | '/settings/identity'
    | '/setup/identity'
    | '/label/'
    | '/settings/'
    | '/setup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SkillRoute: typeof SkillRoute
  LabelProgressRoute: typeof LabelProgressRoute
  SettingsIdentityRoute: typeof SettingsIdentityRoute
  SetupIdentityRoute: typeof SetupIdentityRoute
  LabelIndexRoute: typeof LabelIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill': {
      id: '/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof SkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/label/': {
      id: '/label/'
      path: '/label'
      fullPath: '/label/'
      preLoaderRoute: typeof LabelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/label/progress': {
      id: '/label/progress'
      path: '/label/progress'
      fullPath: '/label/progress'
      preLoaderRoute: typeof LabelProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/identity': {
      id: '/settings/identity'
      path: '/settings/identity'
      fullPath: '/settings/identity'
      preLoaderRoute: typeof SettingsIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/identity': {
      id: '/setup/identity'
      path: '/setup/identity'
      fullPath: '/setup/identity'
      preLoaderRoute: typeof SetupIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecommendationsRoute: RecommendationsRoute,
  SkillRoute: SkillRoute,
  LabelProgressRoute: LabelProgressRoute,
  SettingsIdentityRoute: SettingsIdentityRoute,
  SetupIdentityRoute: SetupIdentityRoute,
  LabelIndexRoute: LabelIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SetupIndexRoute: SetupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
