//! `cargo xtask stage-lock [--check]` over `stage_versions.lock` (architecture §5.5).
//!
//! Each versioned stage pins `(VERSION, blake3 of its quantised golden outputs)`. CI fails when a
//! golden hash changes without a VERSION bump. The stages and their goldens come from
//! `wolluf-engine`.

use std::collections::BTreeMap;
use std::path::Path;

use anyhow::{Context, bail};
use serde::Deserialize;

const LOCK_FILE: &str = "stage_versions.lock";
const BLAKE3_HEX_LEN: usize = 64;

const HEADER: &str = "\
# Stage VERSIONs and golden-output hashes (architecture §5.5, spec 001).
# Generated by `cargo xtask stage-lock`; CI runs `cargo xtask stage-lock --check`.
# A stage whose golden hash changes must bump its VERSION in the same commit.
";

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct Stage {
    pub(crate) id: String,
    pub(crate) version: u32,
    pub(crate) golden: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawLock {
    #[serde(default)]
    stages: BTreeMap<String, RawEntry>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawEntry {
    version: u32,
    golden: String,
}

fn registered_stages() -> Vec<Stage> {
    wolluf_engine::stage::goldens()
        .into_iter()
        .map(|g| Stage {
            id: g.id.as_str().to_owned(),
            version: g.version,
            golden: g.golden,
        })
        .collect()
}

pub(crate) fn run(root: &Path, check: bool) -> anyhow::Result<()> {
    let path = root.join(LOCK_FILE);
    let registered = registered_stages();
    if check {
        let text =
            std::fs::read_to_string(&path).with_context(|| format!("reading {LOCK_FILE}"))?;
        verify(&parse(&text)?, &registered)?;
    } else {
        let rendered = render(&registered);
        let current = std::fs::read_to_string(&path).unwrap_or_default();
        if current != rendered {
            std::fs::write(&path, rendered).with_context(|| format!("writing {LOCK_FILE}"))?;
        }
    }
    println!("{}", summary(registered.len()));
    Ok(())
}

fn summary(count: usize) -> String {
    format!("stage-lock: {count} stages")
}

pub(crate) fn parse(text: &str) -> anyhow::Result<Vec<Stage>> {
    let raw: RawLock = toml::from_str(text).with_context(|| format!("{LOCK_FILE} is malformed"))?;
    raw.stages
        .into_iter()
        .map(|(id, entry)| {
            let is_hex = entry.golden.len() == BLAKE3_HEX_LEN
                && entry
                    .golden
                    .bytes()
                    .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b));
            if !is_hex {
                bail!(
                    "{LOCK_FILE}: stage `{id}` golden must be {BLAKE3_HEX_LEN} lowercase hex chars"
                );
            }
            Ok(Stage {
                id,
                version: entry.version,
                golden: entry.golden,
            })
        })
        .collect()
}

pub(crate) fn verify(locked: &[Stage], registered: &[Stage]) -> anyhow::Result<()> {
    let mut problems = Vec::new();
    for entry in locked {
        if !registered.iter().any(|s| s.id == entry.id) {
            problems.push(format!(
                "stage `{}` is in {LOCK_FILE} but not registered",
                entry.id
            ));
        }
    }
    for stage in registered {
        match locked.iter().find(|e| e.id == stage.id) {
            None => problems.push(format!(
                "stage `{}` is registered but missing from {LOCK_FILE}; run `cargo xtask stage-lock`",
                stage.id
            )),
            Some(entry) if entry.version == stage.version && entry.golden != stage.golden => {
                problems.push(format!(
                    "stage `{}`: golden outputs changed without a VERSION bump (still {})",
                    stage.id, stage.version
                ));
            }
            Some(entry) if entry != stage => problems.push(format!(
                "stage `{}`: {LOCK_FILE} is stale (locked v{}, registered v{}); run `cargo xtask stage-lock`",
                stage.id, entry.version, stage.version
            )),
            Some(_) => {}
        }
    }
    if problems.is_empty() {
        Ok(())
    } else {
        bail!("stage-lock:\n  {}", problems.join("\n  "))
    }
}

pub(crate) fn render(registered: &[Stage]) -> String {
    let mut stages = registered.to_vec();
    stages.sort_by(|a, b| a.id.cmp(&b.id));
    let mut out = HEADER.to_owned();
    for stage in stages {
        // Stage ids contain dots, so the key is always quoted.
        out.push_str(&format!(
            "\n[stages.\"{}\"]\nversion = {}\ngolden = \"{}\"\n",
            stage.id, stage.version, stage.golden
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    const GOLDEN_A: &str = "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262";
    const GOLDEN_B: &str = "0000000000000000000000000000000000000000000000000000000000000001";

    fn stage(id: &str, version: u32, golden: &str) -> Stage {
        Stage {
            id: id.into(),
            version,
            golden: golden.into(),
        }
    }

    #[test]
    fn committed_lock_matches_the_engine() {
        let committed = include_str!("../../stage_versions.lock");
        let registered = registered_stages();
        assert_eq!(committed, render(&registered));
        verify(&parse(committed).unwrap(), &registered).unwrap();
        assert!(registered.iter().any(|s| s.id == "chart_parse"));
        assert_eq!(
            summary(registered.len()),
            format!("stage-lock: {} stages", registered.len())
        );
    }

    #[test]
    fn malformed_lock_fails() {
        for text in [
            "[stages",
            "[stages.\"x.y\"]\nversion = \"one\"\ngolden = \"\"\n",
            "[stages.\"x.y\"]\nversion = 1\n",
            "[stages.\"x.y\"]\nversion = 1\ngolden = \"abc\"\n",
            &format!(
                "[stages.\"x.y\"]\nversion = 1\ngolden = \"{}\"\n",
                GOLDEN_A.to_uppercase()
            ),
            &format!("[stages.\"x.y\"]\nversion = -1\ngolden = \"{GOLDEN_A}\"\n"),
            &format!("[stages.\"x.y\"]\nversion = 1\ngolden = \"{GOLDEN_A}\"\nextra = 2\n"),
            "[stagez]\n",
        ] {
            assert!(parse(text).is_err(), "must reject: {text}");
        }
    }

    #[test]
    fn unregistered_stage_fails() {
        let locked = parse(&render(&[stage("k7.patterns", 1, GOLDEN_A)])).unwrap();
        let err = verify(&locked, &[]).unwrap_err().to_string();
        assert!(
            err.contains("stage `k7.patterns` is in stage_versions.lock but not registered"),
            "{err}"
        );
    }

    #[test]
    fn registered_stage_changes_are_caught() {
        let locked = parse(&render(&[stage("k7.patterns", 1, GOLDEN_A)])).unwrap();
        assert_eq!(locked, [stage("k7.patterns", 1, GOLDEN_A)]);
        verify(&locked, &[stage("k7.patterns", 1, GOLDEN_A)]).unwrap();

        let no_bump = verify(&locked, &[stage("k7.patterns", 1, GOLDEN_B)]).unwrap_err();
        assert!(
            no_bump.to_string().contains("without a VERSION bump"),
            "{no_bump}"
        );
        let stale = verify(&locked, &[stage("k7.patterns", 2, GOLDEN_B)]).unwrap_err();
        assert!(stale.to_string().contains("is stale"), "{stale}");
        let missing = verify(&[], &[stage("k7.patterns", 1, GOLDEN_A)]).unwrap_err();
        assert!(missing.to_string().contains("missing from"), "{missing}");
    }
}
