// @ts-nocheck
// Generated by wolluf-desktop (`cargo xtask bindings`). Do not edit.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	setupDetectInstalls: () => typedError<InstallCandidateDto[], IpcError>(__TAURI_INVOKE("setup_detect_installs")),
	setupSetInstallPath: (path: string) => typedError<InstallDto, IpcError>(__TAURI_INVOKE("setup_set_install_path", { path })),
	setupStatus: () => typedError<SetupStatusDto, IpcError>(__TAURI_INVOKE("setup_status")),
	/**  The whole history: the tray keeps its own cap of finished jobs (spec 005 Behaviour). */
	jobsList: () => typedError<JobDto[], IpcError>(__TAURI_INVOKE("jobs_list")),
	jobsStart: (request: JobStartDto) => typedError<JobId, IpcError>(__TAURI_INVOKE("jobs_start", { request })),
	jobsCancel: (id: JobId) => typedError<null, IpcError>(__TAURI_INVOKE("jobs_cancel", { id })),
	/**
	 *  A pure shell side effect with no app logic, so it lives here and not in `wolluf-app`
	 *  (ADR 0009).
	 */
	appOpenLogsDir: () => typedError<null, IpcError>(__TAURI_INVOKE("app_open_logs_dir")),
	playersListAliases: () => typedError<AliasListDto, IpcError>(__TAURI_INVOKE("players_list_aliases")),
	/**  Persisted profiles plus the virtual All players entry, each with its scopes for `keymode`. */
	playersListProfiles: (keymode: number) => typedError<ProfileEntryDto[], IpcError>(__TAURI_INVOKE("players_list_profiles", { keymode })),
	playersSetProfileAliases: (input: SetProfileAliasesInput) => typedError<ProfileEntryDto, IpcError>(__TAURI_INVOKE("players_set_profile_aliases", { input })),
	playersDecideAlias: (input: DecideAliasInput) => typedError<AliasListDto, IpcError>(__TAURI_INVOKE("players_decide_alias", { input })),
	playersCreateProfile: (input: CreateProfileInput) => typedError<ProfileEntryDto, IpcError>(__TAURI_INVOKE("players_create_profile", { input })),
	playersSetDefault: (profileId: number) => typedError<null, IpcError>(__TAURI_INVOKE("players_set_default", { profileId })),
	/**  Notes, timing lines and layout of `[fromMs, toMs]` for the playfield; no segments. */
	chartWindow: (md5: string, fromMs: number, toMs: number, layoutId: string | null) => typedError<ChartWindowDto, IpcError>(__TAURI_INVOKE("chart_window", { md5, fromMs, toMs, layoutId })),
	labelTaxonomy: (keymode: number) => typedError<PatternDefDto[], IpcError>(__TAURI_INVOKE("label_taxonomy", { keymode })),
	/**  `None` when no chart has a free window left. */
	labelSample: (req: SampleRequestDto) => typedError<{
	anchor: AnchorDto,
	title: string,
	artist: string,
	version: string,
	/**  `scale:level` of the label that placed the chart in its stratum. */
	level: string | null,
	/**  e.g. `dan_07/nps_2`; display only, never persisted. */
	stratum: string,
	played: boolean,
} | null, IpcError>(__TAURI_INVOKE("label_sample", { req })),
	/**  Short keys or full ids to full pattern ids, in input order without repeats. */
	labelResolvePatterns: (keymode: number, tokens: string[]) => typedError<string[], IpcError>(__TAURI_INVOKE("label_resolve_patterns", { keymode, tokens })),
	labelReshape: (anchor: AnchorDto, op: WindowOpDto) => typedError<AnchorDto, IpcError>(__TAURI_INVOKE("label_reshape", { anchor, op })),
	labelSubmit: (req: LabelSubmitDto) => typedError<LabelEventDto, IpcError>(__TAURI_INVOKE("label_submit", { req })),
	labelUndo: (eventId: string) => typedError<null, IpcError>(__TAURI_INVOKE("label_undo", { eventId })),
	labelStats: () => typedError<LabelStatsDto, IpcError>(__TAURI_INVOKE("label_stats")),
	/**  The chart's audio file for the playfield's WebAudio loop; the webview sends only the md5. */
	chartAudio: (md5: string) => typedError<ChartAudioDto, IpcError>(__TAURI_INVOKE("chart_audio", { md5 })),
};

/** Events */
export const events = {
	dataChanged: makeEvent<DataChanged>("data-changed"),
	jobFinished: makeEvent<JobFinished>("job-finished"),
	jobProgress: makeEvent<JobProgress>("job-progress"),
};

/* Types */
export type AliasDecisionInput = {
	aliasId: number,
	/**  `null` clears the decision, handing the alias back to the auto rule (R6). */
	decision: DecisionDto | null,
};

/**  Rows arrive in the R6 order; the UI does not re-sort them. */
export type AliasListDto = {
	selectionVersion: number,
	cfgUsernameAvailable: boolean,
	wizardNeeded: boolean,
	aliases: AliasRowDto[],
};

export type AliasRowDto = {
	aliasId: number,
	/**  Lossy UTF-8 for display only; `aliasId` is the key the UI sends back. */
	rawName: string,
	isEmptyName: boolean,
	normalizedLength: number,
	nPlays: number,
	byKeymode: KeymodeCountDto[],
	firstPlayedAt: string | null,
	lastPlayedAt: string | null,
	nOnline: number,
	nOffline: number,
	nWithReplay: number,
	topCharts: TopChartDto[],
	autoMatch: AutoMatchDto | null,
	decision: DecisionDto | null,
	selected: boolean,
	inSelfProfile: boolean,
};

/**  `[t0Ms, t1Ms)` of one chart. */
export type AnchorDto = {
	md5: string,
	t0Ms: number,
	t1Ms: number,
	/**  1-based, column 1 leftmost, ascending. */
	cols: number[],
};

export type AutoMatchDto = {
	source: MatchSourceDto,
	kind: MatchKindDto,
};

/**  The chart's `AudioFilename` from its set folder, for the webview to decode. */
export type ChartAudioDto = {
	/**  `application/octet-stream` when the extension is not mp3, ogg or wav. */
	mime: string,
	/**  RFC 4648 with padding. */
	base64: string,
};

/**  The first and the last row of the chart (LN tails included); `0, 0` without rows. */
export type ChartSpanDto = {
	firstMs: number,
	endMs: number,
};

/**  What a playfield draws for `[fromMs, toMs]` of one chart. No segments: labelling is blind. */
export type ChartWindowDto = {
	md5: string,
	keymode: number,
	fromMs: number,
	toMs: number,
	/**
	 *  Taps and LN heads in `[fromMs, toMs]` plus LNs whose body enters from before `fromMs`,
	 *  by `(tMs, col)`.
	 */
	notes: NoteDto[],
	/**  The last red line at or before `fromMs`, then every line in `[fromMs, toMs]`. */
	timing: TimingDto[],
	layout: LayoutDto,
	chartSpan: ChartSpanDto,
	audioFilename: string | null,
};

export type ColumnDto = {
	hand: HandDto,
	finger: FingerDto,
};

export type CountDto = {
	key: string,
	count: number,
};

export type CreateProfileInput = {
	label: string,
	aliasIds: number[],
	mergeMode?: MergeModeDto | null,
};

export type DataChanged = DataChangedDto;

export type DataChangedDto = {
	/**  Query-key roots the UI invalidates (`plays`, `players`, `setup`, `jobs`, `library`). */
	domains: string[],
};

export type DecideAliasInput = {
	decisions: AliasDecisionInput[],
	completesWizard: boolean,
};

export type DecisionDto = "me" | "not_me";

export type EntryRefDto = { kind: "profile"; id: number } | { kind: "all_players" };

/**  Wire mirror of core's `ErrorCode`: domain types never derive specta (D13). */
export type ErrorCodeDto = "OSU_DIR_NOT_FOUND" | "UNSUPPORTED_FORMAT" | "PARSE_FAILED" | "OSU_RUNNING" | "CONSENT_REQUIRED" | "SIGNATURE_INVALID" | "NOT_FOUND" | "INVALID_INPUT" | "CONFLICT" | "CANCELLED" | "INTERNAL";

export type FingerDto = "pinky" | "ring" | "middle" | "index" | "thumb";

export type HandDto = "left" | "right" | 
/**  Either thumb may take it. */
"both";

/**
 *  IndexLibrary counters. `failedItems` keeps the name every summary shares, which the job
 *  tray reads without knowing the kind.
 */
export type IndexLibrarySummaryDto = {
	/**  Catalog charts of a keymode with an engine profile. */
	chartsTotal: number,
	parsedNew: number,
	/**  Already parsed, or already failed, under the current `chart_parse` key. */
	skippedMemoized: number,
	/**  Missing from `Songs/` or edited since osu!.db recorded its md5; retried next run. */
	skippedUnavailable: number,
	labelsWritten: number,
	/**  Pattern segments stored this run (`patterns` stage). */
	segmentsWritten: number,
	failedItems: number,
};

export type InstallCandidateDto = {
	path: string,
	source: InstallSourceDto,
	valid: boolean,
	osuDbVersion: number | null,
	/**  File names the UI shows as missing (`osu!.db`, `osu!.exe`, `scores.db`, `directory`). */
	missing: string[],
};

export type InstallDto = {
	id: number,
	rootPath: string,
	osuDbVersion: number | null,
	detectedAt: string,
};

/**  Mirrors 002's `CandidateSource`; the exhaustive `From` keeps them in step. */
export type InstallSourceDto = "env" | "registry" | "local_app_data" | "wsl_user_profile" | "drive_scan" | "program_files";

export type IpcError = {
	code: ErrorCodeDto,
	messageKey: string,
	args: { [key in string]: string },
	details: string | null,
	retryable: boolean,
};

export type JobDto = {
	id: JobId,
	kind: JobKindDto,
	status: JobStatusDto,
	/**  RFC 3339 UTC with milliseconds. */
	started: string | null,
	ended: string | null,
	summary: JobSummaryDto | null,
	error: JobErrorDto | null,
};

/**  Why a job ended `failed` or `cancelled`; the UI localises `messageKey` (§7). */
export type JobErrorDto = {
	code: ErrorCodeDto,
	messageKey: string,
};

export type JobFinished = JobFinishedDto;

export type JobFinishedDto = {
	jobId: JobId,
	status: JobStatusDto,
	failedItems: number,
};

/**  A ULID: sortable by creation time and above 2^53, so it crosses IPC as a string (§8). */
export type JobId = string;

/**  Persisted in `job_run.kind`: stable strings, never renumbered (§11). */
export type JobKindDto = "sync_plays" | 
/**  Chained after every `SyncPlays` (spec 004); never started from IPC. */
"refresh_identity" | 
/**  Chained after every `SyncPlays` too, and startable on its own. */
"index_library";

export type JobProgress = JobProgressDto;

export type JobProgressDto = {
	jobId: JobId,
	kind: JobKindDto,
	stage: JobStageDto,
	done: number,
	total: number,
	etaMs: number | null,
};

/**  The step a job is in; the UI localises it (`jobs.stage.<id>`). */
export type JobStageDto = "catalog" | "ingest" | "archive" | "index";

/**  `JobService::start` input, tagged on `kind` (spec 003 IPC). */
export type JobStartDto = {
	kind: "sync_plays",
} & SyncPlaysStartDto | 
/**  Indexes the charts of the current catalog, whichever install it came from. */
{ kind: "index_library" };

export type JobStatusDto = "queued" | "running" | "ok" | "failed" | "cancelled";

/**  Per-kind result, stored as `job_run.summary_json`. */
export type JobSummaryDto = { kind: "sync_plays"; counters: SyncSummaryDto } | { kind: "index_library"; counters: IndexLibrarySummaryDto };

export type KeymodeCountDto = {
	/**  `k1`..`k16` or `unknown` (`KeymodeBucket`). */
	bucket: string,
	n: number,
};

export type LabelEventDto = {
	/**  The feedback event's ULID; undo takes it back. */
	id: string,
};

/**  Over the self profile's labels that are not undone. Lists are sorted by key. */
export type LabelStatsDto = {
	total: number,
	/**  Answers of "no clear pattern". */
	noPattern: number,
	mixed: number,
	unsure: number,
	thumbLeft: number,
	thumbRight: number,
	perPattern: CountDto[],
	perAxis: CountDto[],
	/**  A chart no longer in the library counts under `unknown`. */
	perStratum: CountDto[],
};

export type LabelSubmitDto = {
	anchor: AnchorDto,
	/**  Full pattern ids of the chart's keymode: at least one, unless `no_pattern`. */
	patterns: string[],
	/**  "No clear pattern": a stored answer with empty `patterns` (a skip is never stored). */
	noPattern: boolean,
	mixed: boolean,
	unsure: boolean,
	/**  `None` is neutral. */
	thumbPref: ThumbPrefDto | null,
};

export type LabelWindowDto = {
	anchor: AnchorDto,
	title: string,
	artist: string,
	version: string,
	/**  `scale:level` of the label that placed the chart in its stratum. */
	level: string | null,
	/**  e.g. `dan_07/nps_2`; display only, never persisted. */
	stratum: string,
	played: boolean,
};

export type LayoutDto = {
	id: string,
	/**  One per column, leftmost first. */
	columns: ColumnDto[],
};

export type MatchKindDto = "equal" | "prefix";

export type MatchSourceDto = "cfg_username" | "linked_account";

export type MergeModeDto = "merged" | "separate";

export type NoteDto = {
	tMs: number,
	/**  0-based, column 0 leftmost. */
	col: number,
	/**  The LN tail; `None` for a tap. */
	endMs: number | null,
};

export type PatternDefDto = {
	id: string,
	axis: string,
	/**  Short key for typing labels. */
	key: string,
	description: string,
};

export type ProfileEntryDto = {
	ref: EntryRefDto,
	profileKind: ProfileKindDto,
	/**  Empty for All players: the UI shows its i18n label. */
	label: string,
	isDefault: boolean,
	mergeMode: MergeModeDto,
	aliasIds: number[],
	scopes: ScopeDto[],
};

export type ProfileKindDto = "self" | "other" | "all_players";

/**  One labelling round. Label bounds are inclusive and match as in the library listing. */
export type SampleRequestDto = {
	keymode: number,
	/**  A `u64` in decimal: the sequence is a pure function of it and the labelled set. */
	seed: string,
	round: number,
	/**  Defaults to the sampler's window. */
	windowMs: number | null,
	scale: string | null,
	levelMin: number | null,
	levelMax: number | null,
	/**
	 *  Windows already shown this session (skips are not stored); labelled ones are always
	 *  avoided.
	 */
	exclude: AnchorDto[],
};

export type ScopeDto = {
	/**  64 hex chars (`ScopeHash`). */
	scopeHash: string,
	aliasIds: number[],
	keymode: number,
};

export type SetProfileAliasesInput = {
	profileId: number,
	aliasIds: number[],
	mergeMode?: MergeModeDto | null,
};

export type SetupStatusDto = {
	install: InstallDto | null,
	identityReady: boolean,
	dataDir: string,
	logsDir: string,
	appVersion: string,
	lastSync: JobDto | null,
};

export type SyncPlaysStartDto = {
	installId: number,
};

/**  SyncPlays step-4 counters (spec 003 Behaviour, "Finish"). */
export type SyncSummaryDto = {
	playsNew: number,
	playsReplayOnly: number,
	playsExisting: number,
	conflicts: number,
	skippedNonMania: number,
	replaysLinked: number,
	osgLinked: number,
	chartsArchived: number,
	chartUnavailable: number,
	chartMd5Mismatch: number,
	orphanReplays: number,
	failedItems: number,
};

export type ThumbPrefDto = "left" | "right";

/**  A red line has `beatLenMs` and `meter`, a green line `sv`. */
export type TimingDto = {
	tMs: number,
	kind: TimingKindDto,
	beatLenMs: number | null,
	meter: number | null,
	sv: number | null,
};

export type TimingKindDto = "red" | "green";

export type TopChartDto = {
	chartMd5: string,
	title: string | null,
	version: string | null,
	n: number,
};

export type WindowOpDto = "widen" | "narrow" | "next" | "prev";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

