// @ts-nocheck
// Generated by wolluf-desktop (`cargo xtask bindings`). Do not edit.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	setupDetectInstalls: () => typedError<InstallCandidateDto[], IpcError>(__TAURI_INVOKE("setup_detect_installs")),
	setupSetInstallPath: (path: string) => typedError<InstallDto, IpcError>(__TAURI_INVOKE("setup_set_install_path", { path })),
	setupStatus: () => typedError<SetupStatusDto, IpcError>(__TAURI_INVOKE("setup_status")),
	/**  The whole history: the tray keeps its own cap of finished jobs (spec 005 Behaviour). */
	jobsList: () => typedError<JobDto[], IpcError>(__TAURI_INVOKE("jobs_list")),
	jobsStart: (request: JobStartDto) => typedError<JobId, IpcError>(__TAURI_INVOKE("jobs_start", { request })),
	jobsCancel: (id: JobId) => typedError<null, IpcError>(__TAURI_INVOKE("jobs_cancel", { id })),
	/**
	 *  A pure shell side effect with no app logic, so it lives here and not in `wolluf-app`
	 *  (ADR 0009).
	 */
	appOpenLogsDir: () => typedError<null, IpcError>(__TAURI_INVOKE("app_open_logs_dir")),
};

/** Events */
export const events = {
	dataChanged: makeEvent<DataChanged>("data-changed"),
	jobFinished: makeEvent<JobFinished>("job-finished"),
	jobProgress: makeEvent<JobProgress>("job-progress"),
};

/* Types */
export type DataChanged = DataChangedDto;

export type DataChangedDto = {
	/**  Query-key roots the UI invalidates (`plays`, `players`, `setup`, `jobs`). */
	domains: string[],
};

/**  Wire mirror of core's `ErrorCode`: domain types never derive specta (D13). */
export type ErrorCodeDto = "OSU_DIR_NOT_FOUND" | "UNSUPPORTED_FORMAT" | "PARSE_FAILED" | "OSU_RUNNING" | "CONSENT_REQUIRED" | "SIGNATURE_INVALID" | "NOT_FOUND" | "INVALID_INPUT" | "CONFLICT" | "CANCELLED" | "INTERNAL";

export type InstallCandidateDto = {
	path: string,
	source: InstallSourceDto,
	valid: boolean,
	osuDbVersion: number | null,
	/**  File names the UI shows as missing (`osu!.db`, `osu!.exe`, `scores.db`, `directory`). */
	missing: string[],
};

export type InstallDto = {
	id: number,
	rootPath: string,
	osuDbVersion: number | null,
	detectedAt: string,
};

/**  Mirrors 002's `CandidateSource`; the exhaustive `From` keeps them in step. */
export type InstallSourceDto = "env" | "registry" | "local_app_data" | "wsl_user_profile" | "drive_scan" | "program_files";

export type IpcError = {
	code: ErrorCodeDto,
	messageKey: string,
	args: { [key in string]: string },
	details: string | null,
	retryable: boolean,
};

export type JobDto = {
	id: JobId,
	kind: JobKindDto,
	status: JobStatusDto,
	/**  RFC 3339 UTC with milliseconds. */
	started: string | null,
	ended: string | null,
	summary: JobSummaryDto | null,
	error: JobErrorDto | null,
};

/**  Why a job ended `failed` or `cancelled`; the UI localises `messageKey` (§7). */
export type JobErrorDto = {
	code: ErrorCodeDto,
	messageKey: string,
};

export type JobFinished = JobFinishedDto;

export type JobFinishedDto = {
	jobId: JobId,
	status: JobStatusDto,
	failedItems: number,
};

/**  A ULID: sortable by creation time and above 2^53, so it crosses IPC as a string (§8). */
export type JobId = string;

/**  Persisted in `job_run.kind`: stable strings, never renumbered (§11). */
export type JobKindDto = "sync_plays" | 
/**  Chained after every `SyncPlays` (spec 004); never started from IPC. */
"refresh_identity";

export type JobProgress = JobProgressDto;

export type JobProgressDto = {
	jobId: JobId,
	kind: JobKindDto,
	stage: JobStageDto,
	done: number,
	total: number,
	etaMs: number | null,
};

/**  The step a job is in; the UI localises it (`jobs.stage.<id>`). */
export type JobStageDto = "catalog" | "ingest" | "archive";

/**  `JobService::start` input, tagged on `kind` (spec 003 IPC). */
export type JobStartDto = {
	kind: "sync_plays",
} & SyncPlaysStartDto;

export type JobStatusDto = "queued" | "running" | "ok" | "failed" | "cancelled";

/**  Per-kind result, stored as `job_run.summary_json`. */
export type JobSummaryDto = { kind: "sync_plays"; counters: SyncSummaryDto };

export type SetupStatusDto = {
	install: InstallDto | null,
	identityReady: boolean,
	dataDir: string,
	logsDir: string,
	appVersion: string,
	lastSync: JobDto | null,
};

export type SyncPlaysStartDto = {
	installId: number,
};

/**  SyncPlays step-4 counters (spec 003 Behaviour, "Finish"). */
export type SyncSummaryDto = {
	playsNew: number,
	playsReplayOnly: number,
	playsExisting: number,
	conflicts: number,
	skippedNonMania: number,
	replaysLinked: number,
	osgLinked: number,
	chartsArchived: number,
	chartUnavailable: number,
	chartMd5Mismatch: number,
	orphanReplays: number,
	failedItems: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

