// @ts-nocheck
// Generated by wolluf-desktop (`cargo xtask bindings`). Do not edit.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	setupDetectInstalls: () => typedError<InstallCandidateDto[], IpcError>(__TAURI_INVOKE("setup_detect_installs")),
	setupSetInstallPath: (path: string) => typedError<InstallDto, IpcError>(__TAURI_INVOKE("setup_set_install_path", { path })),
	setupStatus: () => typedError<SetupStatusDto, IpcError>(__TAURI_INVOKE("setup_status")),
	/**  The whole history: the tray keeps its own cap of finished jobs (spec 005 Behaviour). */
	jobsList: () => typedError<JobDto[], IpcError>(__TAURI_INVOKE("jobs_list")),
	jobsStart: (request: JobStartDto) => typedError<JobId, IpcError>(__TAURI_INVOKE("jobs_start", { request })),
	jobsCancel: (id: JobId) => typedError<null, IpcError>(__TAURI_INVOKE("jobs_cancel", { id })),
	/**
	 *  A pure shell side effect with no app logic, so it lives here and not in `wolluf-app`
	 *  (ADR 0009).
	 */
	appOpenLogsDir: () => typedError<null, IpcError>(__TAURI_INVOKE("app_open_logs_dir")),
	playersListAliases: () => typedError<AliasListDto, IpcError>(__TAURI_INVOKE("players_list_aliases")),
	/**  Persisted profiles plus the virtual All players entry, each with its scopes for `keymode`. */
	playersListProfiles: (keymode: number) => typedError<ProfileEntryDto[], IpcError>(__TAURI_INVOKE("players_list_profiles", { keymode })),
	playersSetProfileAliases: (input: SetProfileAliasesInput) => typedError<ProfileEntryDto, IpcError>(__TAURI_INVOKE("players_set_profile_aliases", { input })),
	playersDecideAlias: (input: DecideAliasInput) => typedError<AliasListDto, IpcError>(__TAURI_INVOKE("players_decide_alias", { input })),
	playersCreateProfile: (input: CreateProfileInput) => typedError<ProfileEntryDto, IpcError>(__TAURI_INVOKE("players_create_profile", { input })),
	playersSetDefault: (profileId: number) => typedError<null, IpcError>(__TAURI_INVOKE("players_set_default", { profileId })),
	/**  Notes, timing lines and layout of `[fromMs, toMs]` for the playfield; no segments. */
	chartWindow: (md5: string, fromMs: number, toMs: number, layoutId: string | null) => typedError<ChartWindowDto, IpcError>(__TAURI_INVOKE("chart_window", { md5, fromMs, toMs, layoutId })),
	labelTaxonomy: (keymode: number) => typedError<PatternDefDto[], IpcError>(__TAURI_INVOKE("label_taxonomy", { keymode })),
	/**  `None` when no chart has a free window left. */
	labelSample: (req: SampleRequestDto) => typedError<{
	anchor: AnchorDto,
	title: string,
	artist: string,
	version: string,
	creator: string,
	/**  stable's cached no-mod star rating; `None` until stable has computed it. */
	stars: number | null,
	/**  `scale:level` of the label that placed the chart in its stratum. */
	level: string | null,
	/**  e.g. `dan_07/nps_2`; display only, never persisted. */
	stratum: string,
	played: boolean,
} | null, IpcError>(__TAURI_INVOKE("label_sample", { req })),
	labelSubmit: (req: LabelSubmitDto) => typedError<LabelEventDto, IpcError>(__TAURI_INVOKE("label_submit", { req })),
	labelUndo: (eventId: string) => typedError<null, IpcError>(__TAURI_INVOKE("label_undo", { eventId })),
	labelStats: () => typedError<LabelStatsDto, IpcError>(__TAURI_INVOKE("label_stats")),
	/**  The chart's audio file for the playfield's WebAudio loop; the webview sends only the md5. */
	chartAudio: (md5: string) => typedError<ChartAudioDto, IpcError>(__TAURI_INVOKE("chart_audio", { md5 })),
	/**  The skin folders of the catalog install, plus the cfg's active skin and mania speed. */
	skinList: () => typedError<SkinListDto, IpcError>(__TAURI_INVOKE("skin_list")),
	/**  One skin's `[Mania]` block and images for `keymode`; the webview sends only the folder name. */
	skinGet: (folder: string, keymode: number) => typedError<SkinDto, IpcError>(__TAURI_INVOKE("skin_get", { folder, keymode })),
	/**
	 *  One synthetic preview per pattern of the keymode, in taxonomy order. `layout_id` `None` draws
	 *  with the stored preference.
	 */
	labelPatternExamples: (keymode: number, layoutId: string | null) => typedError<PatternExampleDto[], IpcError>(__TAURI_INVOKE("label_pattern_examples", { keymode, layoutId })),
	/**
	 *  A free window inside the given chart; `NOT_FOUND` for a chart the catalog has not parsed,
	 *  `CONFLICT` when none of its windows is free.
	 */
	labelWindowAt: (req: WindowAtRequestDto) => typedError<LabelWindowDto, IpcError>(__TAURI_INVOKE("label_window_at", { req })),
	/**  Any eligible chart outside the stratified plan; `None` when no free window is left. */
	labelRandom: (req: RandomRequestDto) => typedError<{
	anchor: AnchorDto,
	title: string,
	artist: string,
	version: string,
	creator: string,
	/**  stable's cached no-mod star rating; `None` until stable has computed it. */
	stars: number | null,
	/**  `scale:level` of the label that placed the chart in its stratum. */
	level: string | null,
	/**  e.g. `dan_07/nps_2`; display only, never persisted. */
	stratum: string,
	played: boolean,
} | null, IpcError>(__TAURI_INVOKE("label_random", { req })),
	/**  The chart osu! is playing, else the user's last replay; probes once per call. */
	labelNowPlaying: (req: NowPlayingRequestDto) => typedError<{
	window: LabelWindowDto,
	source: NowPlayingSourceDto,
} | null, IpcError>(__TAURI_INVOKE("label_now_playing", { req })),
	/**  The window moved to start at `t0Ms`, same length, kept inside the chart. */
	labelMoveWindow: (req: MoveWindowRequestDto) => typedError<AnchorDto, IpcError>(__TAURI_INVOKE("label_move_window", { req })),
	/**  Note density over the whole chart and the user's labelled windows on it. */
	labelChartTimeline: (req: ChartTimelineRequestDto) => typedError<ChartTimelineDto, IpcError>(__TAURI_INVOKE("label_chart_timeline", { req })),
	/**  The chart's `[Events]` background; `None` when it names none or the file cannot be shown. */
	chartBackground: (md5: string) => typedError<{
	/**  `image/png` or `image/jpeg`. */
	mime: string,
	/**  RFC 4648 with padding. */
	base64: string,
	width: number,
	height: number,
} | null, IpcError>(__TAURI_INVOKE("chart_background", { md5 })),
	/**  The keymode's column layout presets, the profile's default first. */
	settingsHandLayouts: (keymode: number) => typedError<HandLayoutDto[], IpcError>(__TAURI_INVOKE("settings_hand_layouts", { keymode })),
	/**  The chosen layout preset id, else the profile's default. */
	settingsGetHandLayout: (keymode: number) => typedError<string, IpcError>(__TAURI_INVOKE("settings_get_hand_layout", { keymode })),
	/**  `INVALID_INPUT` unless `layoutId` is a preset of the keymode. */
	settingsSetHandLayout: (keymode: number, layoutId: string) => typedError<null, IpcError>(__TAURI_INVOKE("settings_set_hand_layout", { keymode, layoutId })),
	/**  The window resized to `[t0Ms, t1Ms)`, kept inside the chart and within the length bounds. */
	labelResizeWindow: (req: ResizeWindowRequestDto) => typedError<AnchorDto, IpcError>(__TAURI_INVOKE("label_resize_window", { req })),
	/**  The catalog row and parse counts the label card and its details dialog show. */
	chartDetails: (md5: string) => typedError<ChartDetailsDto, IpcError>(__TAURI_INVOKE("chart_details", { md5 })),
	/**
	 *  Self plays of the keymode saved since the app started, newest first, with each chart's
	 *  session answer (ADR 0020).
	 */
	sessionPlays: (keymode: number) => typedError<SessionPlaysDto, IpcError>(__TAURI_INVOKE("session_plays", { keymode })),
	/**  Stores a played map's dominant pattern; `pattern` `None` is "no clear pattern". */
	sessionLabelSubmit: (req: SessionLabelSubmitDto) => typedError<LabelEventDto, IpcError>(__TAURI_INVOKE("session_label_submit", { req })),
	sessionLabelUndo: (eventId: string) => typedError<null, IpcError>(__TAURI_INVOKE("session_label_undo", { eventId })),
	/**  Gold and session labelling of the keymode; days are cut at `utcOffsetMin` east of UTC. */
	labelProgress: (keymode: number, utcOffsetMin: number) => typedError<LabelProgressDto, IpcError>(__TAURI_INVOKE("label_progress", { keymode, utcOffsetMin })),
	/**  Whether a finished map flashes the window; off until the user turns it on. */
	settingsGetSessionNotify: () => typedError<boolean, IpcError>(__TAURI_INVOKE("settings_get_session_notify")),
	settingsSetSessionNotify: (on: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("settings_set_session_notify", { on })),
	/**  Into `<data dir>/exports/`, which the opener scope already covers (no save dialog). */
	labelExport: (keymode: number) => typedError<LabelExportDto, IpcError>(__TAURI_INVOKE("label_export", { keymode })),
	appOpenExportsDir: () => typedError<null, IpcError>(__TAURI_INVOKE("app_open_exports_dir")),
};

/** Events */
export const events = {
	dataChanged: makeEvent<DataChanged>("data-changed"),
	jobFinished: makeEvent<JobFinished>("job-finished"),
	jobProgress: makeEvent<JobProgress>("job-progress"),
	sessionPlayAdded: makeEvent<SessionPlayAdded>("session-play-added"),
};

/* Types */
export type AliasDecisionInput = {
	aliasId: number,
	/**  `null` clears the decision, handing the alias back to the auto rule (R6). */
	decision: DecisionDto | null,
};

/**  Rows arrive in the R6 order; the UI does not re-sort them. */
export type AliasListDto = {
	selectionVersion: number,
	cfgUsernameAvailable: boolean,
	wizardNeeded: boolean,
	aliases: AliasRowDto[],
};

export type AliasRowDto = {
	aliasId: number,
	/**  Lossy UTF-8 for display only; `aliasId` is the key the UI sends back. */
	rawName: string,
	isEmptyName: boolean,
	normalizedLength: number,
	nPlays: number,
	byKeymode: KeymodeCountDto[],
	firstPlayedAt: string | null,
	lastPlayedAt: string | null,
	nOnline: number,
	nOffline: number,
	nWithReplay: number,
	topCharts: TopChartDto[],
	autoMatch: AutoMatchDto | null,
	decision: DecisionDto | null,
	selected: boolean,
	inSelfProfile: boolean,
};

/**  `[t0Ms, t1Ms)` of one chart. */
export type AnchorDto = {
	md5: string,
	t0Ms: number,
	t1Ms: number,
	/**  1-based, column 1 leftmost, ascending. */
	cols: number[],
};

export type AutoMatchDto = {
	source: MatchSourceDto,
	kind: MatchKindDto,
};

/**  The chart's `AudioFilename` from its set folder, for the webview to decode. */
export type ChartAudioDto = {
	/**  `application/octet-stream` when the extension is not mp3, ogg or wav. */
	mime: string,
	/**  RFC 4648 with padding. */
	base64: string,
};

/**
 *  What the label card and its details dialog show of one chart: the osu!.db row plus the
 *  parse's counts. osu!.db fields a map leaves empty come back `None` or empty.
 */
export type ChartDetailsDto = {
	md5: string,
	title: string,
	artist: string,
	creator: string,
	/**  The difficulty name. */
	version: string,
	source: string | null,
	tags: string[],
	/**  stable's cached no-mod star rating; `None` until stable has computed it. */
	stars: number | null,
	od: number | null,
	hp: number | null,
	lengthMs: number,
	/**  Over the red lines up to the last row; `None` without one. */
	bpmMin: number | null,
	bpmMax: number | null,
	nNotes: number,
	nLn: number,
	setId: number | null,
	beatmapId: number | null,
};

/**
 *  The chart's `[Events]` background from its set folder, for the webview to show as a `data:`
 *  URL; the bytes decided the type and size.
 */
export type ChartImageDto = {
	/**  `image/png` or `image/jpeg`. */
	mime: string,
	/**  RFC 4648 with padding. */
	base64: string,
	width: number,
	height: number,
};

/**  Values match the persisted and exported ids. */
export type ChartPickDto = 
/**  The stratified sampler's round. */
"sampled" | 
/**  Any eligible chart, outside the stratified plan. */
"random" | 
/**  The chart osu! is playing, or the newest self replay. */
"now_playing" | 
/**  A map opened from the session list. */
"session";

/**  The first and the last row of the chart (LN tails included); `0, 0` without rows. */
export type ChartSpanDto = {
	firstMs: number,
	endMs: number,
};

/**  A whole chart at a glance: where its notes are and which windows the user labelled. */
export type ChartTimelineDto = {
	/**  The first row. */
	firstMs: number,
	/**  One past the last row: the latest a window may end. */
	endMs: number,
	/**  Notes (taps and LN heads) per equal slice of `[firstMs, endMs)`, earliest first. */
	density: number[],
	/**  The self profile's labels on this chart that are not undone, by start. */
	labelled: SpanDto[],
};

export type ChartTimelineRequestDto = {
	keymode: number,
	md5: string,
	buckets: number,
};

/**  What a playfield draws for `[fromMs, toMs]` of one chart. No segments: labelling is blind. */
export type ChartWindowDto = {
	md5: string,
	keymode: number,
	fromMs: number,
	toMs: number,
	/**
	 *  Taps and LN heads in `[fromMs, toMs]` plus LNs whose body enters from before `fromMs`,
	 *  by `(tMs, col)`.
	 */
	notes: NoteDto[],
	/**  The last red line at or before `fromMs`, then every line in `[fromMs, toMs]`. */
	timing: TimingDto[],
	layout: LayoutDto,
	chartSpan: ChartSpanDto,
	audioFilename: string | null,
};

export type ColumnDto = {
	hand: HandDto,
	finger: FingerDto,
};

export type CountDto = {
	key: string,
	count: number,
};

export type CreateProfileInput = {
	label: string,
	aliasIds: number[],
	mergeMode?: MergeModeDto | null,
};

export type DataChanged = DataChangedDto;

export type DataChangedDto = {
	/**  Query-key roots the UI invalidates (`plays`, `players`, `setup`, `jobs`, `library`). */
	domains: string[],
};

/**  Labelled on one local day, oldest day first. */
export type DayCountDto = {
	/**  `YYYY-MM-DD` at the request's UTC offset. */
	day: string,
	gold: number,
	/**
	 *  Maps whose effective session answer was given that day: a relabel moves its map, so the
	 *  days sum to `session_labels` over the window.
	 */
	session: number,
};

export type DecideAliasInput = {
	decisions: AliasDecisionInput[],
	completesWizard: boolean,
};

export type DecisionDto = "me" | "not_me";

export type EntryRefDto = { kind: "profile"; id: number } | { kind: "all_players" };

/**  Wire mirror of core's `ErrorCode`: domain types never derive specta (D13). */
export type ErrorCodeDto = "OSU_DIR_NOT_FOUND" | "UNSUPPORTED_FORMAT" | "PARSE_FAILED" | "OSU_RUNNING" | "CONSENT_REQUIRED" | "SIGNATURE_INVALID" | "NOT_FOUND" | "INVALID_INPUT" | "CONFLICT" | "CANCELLED" | "INTERNAL";

export type FingerDto = "pinky" | "ring" | "middle" | "index" | "thumb";

export type HandDto = "left" | "right" | 
/**  Either thumb may take it. */
"both";

/**  A column layout preset: which hand and finger press each column. */
export type HandLayoutDto = {
	id: string,
	/**  One per column, leftmost first. */
	columns: ColumnDto[],
};

/**
 *  IndexLibrary counters. `failedItems` keeps the name every summary shares, which the job
 *  tray reads without knowing the kind.
 */
export type IndexLibrarySummaryDto = {
	/**  Catalog charts of a keymode with an engine profile. */
	chartsTotal: number,
	parsedNew: number,
	/**  Already parsed, or already failed, under the current `chart_parse` key. */
	skippedMemoized: number,
	/**  Missing from `Songs/` or edited since osu!.db recorded its md5; retried next run. */
	skippedUnavailable: number,
	labelsWritten: number,
	/**  Pattern segments stored this run (`patterns` stage). */
	segmentsWritten: number,
	failedItems: number,
};

export type InstallCandidateDto = {
	path: string,
	source: InstallSourceDto,
	valid: boolean,
	osuDbVersion: number | null,
	/**  File names the UI shows as missing (`osu!.db`, `osu!.exe`, `scores.db`, `directory`). */
	missing: string[],
};

export type InstallDto = {
	id: number,
	rootPath: string,
	osuDbVersion: number | null,
	detectedAt: string,
};

/**  Mirrors 002's `CandidateSource`; the exhaustive `From` keeps them in step. */
export type InstallSourceDto = "env" | "registry" | "local_app_data" | "wsl_user_profile" | "drive_scan" | "program_files";

export type IpcError = {
	code: ErrorCodeDto,
	messageKey: string,
	args: { [key in string]: string },
	details: string | null,
	retryable: boolean,
};

export type JobDto = {
	id: JobId,
	kind: JobKindDto,
	status: JobStatusDto,
	/**  RFC 3339 UTC with milliseconds. */
	started: string | null,
	ended: string | null,
	summary: JobSummaryDto | null,
	error: JobErrorDto | null,
};

/**  Why a job ended `failed` or `cancelled`; the UI localises `messageKey` (§7). */
export type JobErrorDto = {
	code: ErrorCodeDto,
	messageKey: string,
};

export type JobFinished = JobFinishedDto;

export type JobFinishedDto = {
	jobId: JobId,
	status: JobStatusDto,
	failedItems: number,
};

/**  A ULID: sortable by creation time and above 2^53, so it crosses IPC as a string (§8). */
export type JobId = string;

/**  Persisted in `job_run.kind`: stable strings, never renumbered (§11). */
export type JobKindDto = "sync_plays" | 
/**  Chained after every `SyncPlays` (spec 004); never started from IPC. */
"refresh_identity" | 
/**  Chained after every `SyncPlays` too, and startable on its own. */
"index_library";

export type JobProgress = JobProgressDto;

export type JobProgressDto = {
	jobId: JobId,
	kind: JobKindDto,
	stage: JobStageDto,
	done: number,
	total: number,
	etaMs: number | null,
};

/**  The step a job is in; the UI localises it (`jobs.stage.<id>`). */
export type JobStageDto = "catalog" | "ingest" | "archive" | "index";

/**  `JobService::start` input, tagged on `kind` (spec 003 IPC). */
export type JobStartDto = {
	kind: "sync_plays",
} & SyncPlaysStartDto | 
/**  Indexes the charts of the current catalog, whichever install it came from. */
{ kind: "index_library" };

export type JobStatusDto = "queued" | "running" | "ok" | "failed" | "cancelled";

/**  Per-kind result, stored as `job_run.summary_json`. */
export type JobSummaryDto = { kind: "sync_plays"; counters: SyncSummaryDto } | { kind: "index_library"; counters: IndexLibrarySummaryDto };

export type KeymodeCountDto = {
	/**  `k1`..`k16` or `unknown` (`KeymodeBucket`). */
	bucket: string,
	n: number,
};

export type LabelEventDto = {
	/**  The feedback event's ULID; undo takes it back. */
	id: string,
};

export type LabelExportDto = {
	path: string,
	rows: number,
};

/**
 *  The self profile's labelling of one keymode, over labels no undo cancels. Count lists are
 *  sorted by key.
 */
export type LabelProgressDto = {
	goldTotal: number,
	goldNoPattern: number,
	/**  Gold labels whose selection is blind (ADR 0021). */
	goldBlind: number,
	/**  Gold labels by selection, as in `LabelStatsDto`. */
	perSelection: SelectionCountDto[],
	perPattern: CountDto[],
	perAxis: CountDto[],
	/**  Maps with a session answer; relabelling a map does not add one. */
	sessionLabels: number,
	perDay: DayCountDto[],
	/**  Newest first. */
	recent: RecentLabelDto[],
};

/**
 *  How a gold window was chosen (ADR 0021): blind when the chart is `sampled` or `random` and
 *  the window is the one offered.
 */
export type LabelSelectionDto = {
	pick: ChartPickDto,
	window: WindowPickDto,
};

/**  Over the self profile's labels that are not undone. Lists are sorted by key. */
export type LabelStatsDto = {
	total: number,
	/**  Answers of "no clear pattern". */
	noPattern: number,
	mixed: number,
	unsure: number,
	thumbLeft: number,
	thumbRight: number,
	perPattern: CountDto[],
	perAxis: CountDto[],
	/**  A chart no longer in the library counts under `unknown`. */
	perStratum: CountDto[],
	/**  Labels whose selection is blind (ADR 0021); every count above includes the others too. */
	blind: number,
	/**  Unknown first, then by pick and window. */
	perSelection: SelectionCountDto[],
};

export type LabelSubmitDto = {
	anchor: AnchorDto,
	/**  Full pattern ids of the chart's keymode: at least one, unless `no_pattern`. */
	patterns: string[],
	/**  "No clear pattern": a stored answer with empty `patterns` (a skip is never stored). */
	noPattern: boolean,
	mixed: boolean,
	unsure: boolean,
	/**  `None` is neutral. */
	thumbPref: ThumbPrefDto | null,
	/**  Declared by the client; the service checks only what it can know (ADR 0021). */
	selection: LabelSelectionDto,
};

export type LabelWindowDto = {
	anchor: AnchorDto,
	title: string,
	artist: string,
	version: string,
	creator: string,
	/**  stable's cached no-mod star rating; `None` until stable has computed it. */
	stars: number | null,
	/**  `scale:level` of the label that placed the chart in its stratum. */
	level: string | null,
	/**  e.g. `dan_07/nps_2`; display only, never persisted. */
	stratum: string,
	played: boolean,
};

export type LayoutDto = {
	id: string,
	/**  One per column, leftmost first. */
	columns: ColumnDto[],
};

/**  `None` where `skin.ini` sets no colour, so the renderer keeps its own. */
export type ManiaColoursDto = {
	/**
	 *  `Colour1` is `column[0]`. Raw alpha: column backgrounds draw with alpha A², and alpha 0
	 *  hides them (research 06, Geometry).
	 */
	column: ([number, number, number, number] | null)[],
	/**  Alpha 0 is already sent as 255, as stable does for these colours. */
	columnLine: [number, number, number, number] | null,
	judgementLine: [number, number, number, number] | null,
	barline: [number, number, number, number] | null,
	hold: [number, number, number, number] | null,
};

/**
 *  The `[Mania]` block for the requested key count, or lazer's all-defaults block when the skin
 *  has none (research 06).
 */
export type ManiaConfigDto = {
	keys: number,
	columnWidth: (number | null)[],
	/**  `keys - 1` gaps. */
	columnSpacing: (number | null)[],
	/**  `keys + 1` lines. */
	columnLineWidth: (number | null)[],
	/**  Judgement line y from the top, already clamped to 240–480. */
	hitPosition: number | null,
	lightPosition: number | null,
	widthForNoteHeightScale: number | null,
	noteBodyStyle: NoteBodyStyleDto,
	judgementLine: boolean,
	keysUnderNotes: boolean,
	upsideDown: boolean,
	barlineHeight: number | null,
	colours: ManiaColoursDto,
};

export type MatchKindDto = "equal" | "prefix";

export type MatchSourceDto = "cfg_username" | "linked_account";

export type MergeModeDto = "merged" | "separate";

/**  `anchor` moved to start at `t0Ms`, keeping its length. */
export type MoveWindowRequestDto = {
	anchor: AnchorDto,
	t0Ms: number,
};

/**  lazer's values; the wiki's 0/1/2 disagree and are unverified (research 06). */
export type NoteBodyStyleDto = "stretch" | "repeat_top" | "repeat_bottom" | "repeat_top_and_bottom";

export type NoteDto = {
	tMs: number,
	/**  0-based, column 0 leftmost. */
	col: number,
	/**  The LN tail; `None` for a tap. */
	endMs: number | null,
};

export type NowPlayingDto = {
	window: LabelWindowDto,
	source: NowPlayingSourceDto,
};

export type NowPlayingRequestDto = {
	keymode: number,
	/**  Windows already shown this session, so a skipped one is not offered again. */
	exclude: AnchorDto[],
};

export type NowPlayingSourceDto = 
/**  osu! stable's window title named the chart. */
"osuWindow" | 
/**  The newest replay in `Data/r` played by the self profile. */
"lastReplay";

export type PatternDefDto = {
	id: string,
	axis: string,
	/**  Short key for typing labels. */
	key: string,
	description: string,
};

/**  A synthetic chart that shows one pattern; `window.fromMs..=toMs` is the span to draw. */
export type PatternExampleDto = {
	id: string,
	window: ChartWindowDto,
};

export type ProfileEntryDto = {
	ref: EntryRefDto,
	profileKind: ProfileKindDto,
	/**  Empty for All players: the UI shows its i18n label. */
	label: string,
	isDefault: boolean,
	mergeMode: MergeModeDto,
	aliasIds: number[],
	scopes: ScopeDto[],
};

export type ProfileKindDto = "self" | "other" | "all_players";

/**
 *  Any eligible chart of the keymode, outside the stratified plan: it neither follows nor
 *  consumes the sampler's rounds.
 */
export type RandomRequestDto = {
	keymode: number,
	/**  A `u64` in decimal. */
	seed: string,
	round: number,
	windowMs: number | null,
	exclude: AnchorDto[],
};

export type RecentLabelDto = {
	eventId: string,
	md5: string,
	/**  `None` once the chart left the library. */
	title: string | null,
	version: string | null,
	patterns: string[],
	noPattern: boolean,
	at: string,
};

/**
 *  `anchor` resized to `[t0Ms, t1Ms)`: the edge that moved from the anchor's is clamped to
 *  the chart and to the window length bounds.
 */
export type ResizeWindowRequestDto = {
	anchor: AnchorDto,
	t0Ms: number,
	t1Ms: number,
};

/**  One labelling round. Label bounds are inclusive and match as in the library listing. */
export type SampleRequestDto = {
	keymode: number,
	/**  A `u64` in decimal: the sequence is a pure function of it and the labelled set. */
	seed: string,
	round: number,
	/**  Defaults to the sampler's window. */
	windowMs: number | null,
	scale: string | null,
	levelMin: number | null,
	levelMax: number | null,
	/**
	 *  Windows already shown this session (skips are not stored); labelled ones are always
	 *  avoided.
	 */
	exclude: AnchorDto[],
};

export type ScopeDto = {
	/**  64 hex chars (`ScopeHash`). */
	scopeHash: string,
	aliasIds: number[],
	keymode: number,
};

/**
 *  Gold labels with one selection; `selection` `None` counts labels stored before ADR 0021,
 *  whose origin is unknown.
 */
export type SelectionCountDto = {
	selection: LabelSelectionDto | null,
	count: number,
};

/**  A chart's effective session answer: the latest one no undo cancels. */
export type SessionLabelDto = {
	eventId: string,
	/**  `None` is "no clear pattern". */
	pattern: string | null,
	at: string,
};

/**  The dominant pattern of a map the user played (ADR 0020). Never part of the gold set. */
export type SessionLabelSubmitDto = {
	keymode: number,
	md5: string,
	/**  The self play the answer follows, hex as `SessionPlayDto.playId`. */
	playId: string | null,
	/**  A full pattern id of the keymode; `None` is "no clear pattern". */
	pattern: string | null,
};

export type SessionPlayAdded = SessionPlayAddedDto;

/**  A self play saved since the app started that the UI has not been told about (ADR 0020). */
export type SessionPlayAddedDto = {
	playId: string,
	md5: string,
};

export type SessionPlayDto = {
	/**  Hex `PlayId`, as `session_label_submit` takes it back. */
	playId: string,
	md5: string,
	playedAt: string,
	title: string,
	artist: string,
	version: string,
	creator: string,
	/**  stable's cached no-mod star rating; `None` until stable has computed it. */
	stars: number | null,
	keymode: number,
	/**  osu! beatmapset id, for the website link; `None` for an unsubmitted map. */
	setId: number | null,
	/**  The chart's effective session answer, from this session or an earlier one. */
	label: SessionLabelDto | null,
	/**
	 *  The self profile's gold windows on the chart that no undo cancels. Information only:
	 *  they never resolve the row (ADR 0020).
	 */
	goldWindows: number,
};

export type SessionPlaysDto = {
	/**  When the app started; plays from then on belong to the session. */
	startedAt: string,
	/**  Newest first; one row per play, so a map played twice is listed twice. */
	plays: SessionPlayDto[],
};

export type SetProfileAliasesInput = {
	profileId: number,
	aliasIds: number[],
	mergeMode?: MergeModeDto | null,
};

export type SetupStatusDto = {
	install: InstallDto | null,
	identityReady: boolean,
	dataDir: string,
	logsDir: string,
	appVersion: string,
	lastSync: JobDto | null,
};

export type SkinDiagnosticDto = {
	/**  A stable `skin.*` id. */
	code: string,
	slot: string | null,
};

export type SkinDto = {
	folder: string,
	name: string | null,
	/**  `[General] Version`; 1.0 when absent, 2.7 for `latest` or without `skin.ini`. */
	version: number | null,
	config: ManiaConfigDto,
	/**  Resolved slots only; a slot absent here is drawn procedurally. */
	images: SkinImageRefDto[],
	/**  Each resolved file once, shared by every slot that resolves to it. */
	files: SkinFileDto[],
	diagnostics: SkinDiagnosticDto[],
	effects: SkinEffectsDto,
};

/**
 *  What the Label preview's autoplay effects need besides images, in stable's 480-high units
 *  with lazer's defaults applied (research 06).
 */
export type SkinEffectsDto = {
	/**  `[Mania] ScorePosition`: hit-burst centre, y from the top. */
	scorePosition: number | null,
	/**  `[Mania] ComboPosition`: combo counter centre, y from the top. */
	comboPosition: number | null,
	/**  Per column; 0 means the column width. */
	lightingNWidth: (number | null)[],
	lightingLWidth: (number | null)[],
	/**  `ColourLight1` is `[0]`, the stage light's tint; alpha 0 already sent as 255. */
	lightColours: ([number, number, number, number] | null)[],
	/**  `[Fonts] ComboOverlap`: px the combo digits overlap; negative adds a gap. */
	comboOverlap: number | null,
};

export type SkinEntryDto = {
	/**  What `skin_get` takes; `[General] Name` is neither unique nor the folder (research 06). */
	folder: string,
	name: string | null,
	/**  Key counts with a `[Mania]` block; empty without a readable `skin.ini`. */
	keymodes: number[],
	/**  Opaque cache key that changes when `skin.ini` is edited (ADR 0019). */
	iniMtime: string | null,
};

/**  A PNG or JPEG checked by its header, never decoded here; the webview decodes it. */
export type SkinFileDto = {
	mime: string,
	/**  2 for an `@2x` file: its display size is the pixel size halved. */
	scale: number,
	width: number,
	height: number,
	/**  RFC 4648 with padding. */
	base64: string,
};

/**
 *  `slot` ids: `note.{i}`, `note.{i}.head`, `note.{i}.tail`, `body.{i}`, `key.{i}`,
 *  `key.{i}.down`, `stage.{left,right,bottom,hint,light}`, with 0-based columns, and
 *  `hit.{0,50,100,200,300,300g}`, `combo.{0-9}`, `lighting.{n,l}.{frame}` with 0-based frames.
 */
export type SkinImageRefDto = {
	slot: string,
	/**  Index into `SkinDto::files`. */
	file: number,
};

export type SkinListDto = {
	/**  By folder name, byte order. */
	skins: SkinEntryDto[],
	/**  The cfg `Skin`, only when it names a listed folder byte for byte. */
	current: string | null,
	/**  The cfg `ManiaSpeed`, 1–40. */
	maniaSpeed: number | null,
	maniaSpeedBpmScale: boolean | null,
};

/**  `[t0Ms, t1Ms)`. */
export type SpanDto = {
	t0Ms: number,
	t1Ms: number,
};

export type SyncPlaysStartDto = {
	installId: number,
};

/**  SyncPlays step-4 counters (spec 003 Behaviour, "Finish"). */
export type SyncSummaryDto = {
	playsNew: number,
	playsReplayOnly: number,
	playsExisting: number,
	conflicts: number,
	skippedNonMania: number,
	replaysLinked: number,
	osgLinked: number,
	chartsArchived: number,
	chartUnavailable: number,
	chartMd5Mismatch: number,
	orphanReplays: number,
	failedItems: number,
};

export type ThumbPrefDto = "left" | "right";

/**  A red line has `beatLenMs` and `meter`, a green line `sv`. */
export type TimingDto = {
	tMs: number,
	kind: TimingKindDto,
	beatLenMs: number | null,
	meter: number | null,
	sv: number | null,
};

export type TimingKindDto = "red" | "green";

export type TopChartDto = {
	chartMd5: string,
	title: string | null,
	version: string | null,
	n: number,
};

/**  A window inside one chart the user picked, start chosen like the sampler's. */
export type WindowAtRequestDto = {
	keymode: number,
	md5: string,
	/**  A `u64` in decimal. */
	seed: string,
	windowMs: number | null,
	exclude: AnchorDto[],
};

export type WindowPickDto = 
/**  Exactly the window the pick offered. */
"sampled" | 
/**  Moved, resized, widened, narrowed or shifted by the labeller. */
"moved";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

